# Generated by Django 4.2.14 on 2025-08-13 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fdc_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('serving_size', models.FloatField(blank=True, help_text='grams', null=True)),
                ('serving_unit', models.CharField(blank=True, max_length=32, null=True)),
                ('data_source', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(help_text='kcal per 100g')),
                ('protein', models.FloatField(help_text='g per 100g')),
                ('fat', models.FloatField(help_text='g per 100g')),
                ('carbs', models.FloatField(help_text='g per 100g')),
                ('fiber', models.FloatField(blank=True, help_text='g per 100g', null=True)),
                ('sugar', models.FloatField(blank=True, help_text='g per 100g', null=True)),
                ('sodium', models.FloatField(blank=True, help_text='mg per 100g', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='grams consumed')),
                ('meal_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='nutrients',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='core.nutrients'),
        ),
    ]
