# Generated by Django 4.2.14 on 2025-08-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrients',
            name='calories',
            field=models.FloatField(blank=True, help_text='kcal per 100g', null=True),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='carbs',
            field=models.FloatField(blank=True, help_text='g per 100g', null=True),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='fat',
            field=models.FloatField(blank=True, help_text='g per 100g', null=True),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='protein',
            field=models.FloatField(blank=True, help_text='g per 100g', null=True),
        ),
    ]
