name: Flutter Web CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
        working-directory: frontend
      - name: Analyze
        run: flutter analyze
        working-directory: frontend
      - name: Build web (release)
        run: flutter build web --release
        working-directory: frontend
