name: Django CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=backend.settings" >> $GITHUB_ENV
          echo "SECRET_KEY=dummy" >> $GITHUB_ENV
          echo "DEBUG=1" >> $GITHUB_ENV
      - name: Run migrations
        run: python manage.py migrate --noinput
      - name: Run tests
        run: python manage.py test
